### ISSUE TITLE
本当にどうでも良いメモ書きIssues

### ISSUE THREAD

**Issue by lef2** [lef2/suburi#147]
2020/5/25
日程の提示で日付に文字が入ってるんだけどこれ何？
2020/5/B -> beginning 初旬
2020/5/M -> middle 中旬
2020/5/E -> end 下旬

このパターンもあるらしい。。。
上旬・・・「first」「early」
下旬・・・「last」「late」

**Comment by kansya** [comment]
なぜテスト全部を自分が担当して、なおかつ新人のプログラミングを教育しながら、新人が楽しそうに実装しているのを見て内心嫌な思いいっぱいだけど笑顔で対応しているのだろうか。。。不明。。。

**Comment by kansya** [comment]
◼️画像(PNMフォーマット)のデータ量の求め方
１、全画素数について算出
全画素数(dotとかpixel) = タテmm * ヨコmm * 25.4inch/mm * 600dpi

２、1画素の階調を考慮して、データ量の算出
データ量(byte) = 全画素数 * 1画素における階調で求まるビット数

補足)
1画素2値なら1bit
1画素4値なら2bit
1画素16値なら4bit

ただし主走査のバイト数は4倍にならないといけないので、上の手順は性格ではない。正しい手順は下記。
１、主走査の画素数を求める。(MemorySize...)
２、主走査の画素数と、1画素における階調で求まるビット数を掛け合わせる。
３、4バイト長に調整する。
４、副走査の画素数と掛け合わせる。

となる。

**Comment by lef2** [comment]
障害解析依頼メール
【依頼内容/質問内容】

【背景】

【納期】

【問い合わせ先】

**Comment by lef2** [comment]
スレッド処理のパターン

1,イベント処理
→ディスパッチャからイベントが送られてきて、場合によってはステータスを変化させる。

2,ステータス処理
→ステータスの変化を受け取って、処理を変化させる。処理が完了するとまたステータスを変化させる。

**Comment by lef2** [comment]
jpegtranでjepg画像を回転する
https://www.ijg.org/files/

$ tar -zxvf jpegsrc.v6b.tar.gz
$ ./configure
$ make
$ ./jpegtran -v
$ cp jpegtran ~/bin

$ jpegtran -rotate 90 -copy all input.jpg > output.jpg

**Comment by lef2** [comment]
問い合わせ汎用

認識不足で申し訳ありませんが、
どのような仕様が存在するのか何を見ればわかるでしょうか？
